### ISSUE TITLE
bug: types not included in NPM package

### ISSUE THREAD

**Issue by jorroll** [lukasbach/react-accessible-menu#1]
Hey there,

Looks like the published NPM package doesn't properly point to the typescript types. You can [see the published package here](https://www.runpkg.com/?react-accessible-menu@1.0.0/lib/cjs/index.js). The package.json includes a typings entry pointing to `lib/types/index.d.ts` except there is no `lib/types` folder included in the package. This can be fixed by instead pointing to `lib/esm/index.d.ts` which does exist in the package.

Thanks!

**Comment by lukasbach** [comment]
My bad! They are available as of v1.0.1.
