### ISSUE TITLE
`useMenuHotkeys` event listeners are getting in the way 

### ISSUE THREAD

**Issue by jorroll** [lukasbach/react-accessible-menu#2]
At the moment, this component is capturing a wide array of keypresses while it is focused and cancelling them. In my case, [this line](https://github.com/lukasbach/react-accessible-menu/blob/main/src/useMenuHotkeys.ts#L51) is preventing my app from responding to hotkeys if this component has focus and I'd like to disable that unused functionality (i.e. `/^[a-zA-Z0-9]$/.test(e.key)`).

More broadly though, it seems like any library event listener should be configurable since it stands a chance of getting in the way of the consumer's project. I'm also skeptical that a library package should ever subscribe to events outside of it's scope without being given explicit permission (e.g. by having the consumer use an initialization hook). Is there a particular reason why this package is adding an event listener to `document` instead of to `containerRef`?

Of course, in spite of these issues I really appreciate that you took the time to publish this package. Very helpful. Ultimately I can just fork it and fix the issues myself, but would you accept a PR to address these issues?

**Comment by lukasbach** [comment]
Hi @jorroll, I'm not sure anymore why I decided to attach the event listeners to the document back then, I changed it to have them hook onto the containerRef instead. I also added an option (`ignoreSearchByKey`) to opt out of this listener logic specifically. The changes are available as of v1.0.1.
