### ISSUE TITLE
bug: looks like Menu component should be generic but isn't

### ISSUE THREAD

**Issue by jorroll** [lukasbach/react-accessible-menu#3]
The `Menu` component exported by this package has the type `React.ForwardRefExoticComponent<MenuProps<HTMLDivElement, any> & React.RefAttributes<MenuImperativeHandle<any>>>`. This means that it's direct child node needs to be a `<div>` element. That seems like something that should be configurable. This being said, it's pretty easy to work around with some type casting like so:

```ts
import {
  Menu as _Menu,
  MenuImperativeHandle,
  MenuProps,
} from "react-accessible-menu";

const Menu = _Menu as unknown as React.ForwardRefExoticComponent<
  MenuProps<HTMLUListElement, any> &
    React.RefAttributes<MenuImperativeHandle<any>>
>;
```

Here we're casting it to expect a `<ul>` element instead of a `<div>` element.

**Comment by lukasbach** [comment]
Yeah, making forwarded components with generic types is hard 😅 Anyway, Menu should now be properly typed with a generic as of v1.0.1.
